class DBCredentials:
	CUIT = None
	MUTUAL = None
	DATA_BASE = None
	USER_DB = None
	PASS_DB = None
	EMAIL_RECIPIENTS = None
	EMAIL_ENVIO_CC = None
	USUARIO_SERVICIO_BICA = None
	PASSWORD_SERVICIO_BICA = None
	CONVENIO = None
